name: CI

on:
  push:
    branches:
      - vanilla
      - vanilla-dev
      - expansion
      - expansion-dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout agbcc
        uses: actions/checkout@v3
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Checkout poryscript
        uses: actions/checkout@v3
        with:
          path: poryscript
          repository: huderlem/poryscript

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install poryscript
        run: |
          go build
          ./install.sh ../
        working-directory: poryscript

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc


      - name: Agbcc
        run: make -j${nproc} -O all

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all

      # - name: Test
      #   run: |
      #     make -j${nproc} -O pokeemerald-test.elf
      #     make -j${nproc} check
